package com.lambdb.core.query;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Optional;

/**
 * Query.java
 * Author: Vishwas Karode
 * Description:
 * A record class to represent a parsed LAMBQL query in a structured format.
 * Utilizes static factory methods for robust construction, avoiding Java's type erasure issues
 * with overloaded constructors. This class holds all components of a parsed query,
 * including support for document data, filters, update data, and projection fields.
 */
public record Query(
        QueryType type,                     // The type of the query (e.g., INSERT, SELECT)
        String collectionName,              // The name of the collection the query targets
        Optional<String> documentData,      // Optional: Raw JSON string for INSERT or full document for UPDATE (if replacing)
        Optional<JsonNode> filter,          // Optional: Parsed JSON for WHERE clause conditions (e.g., {"name": "Alice"})
        Optional<JsonNode> updateData,      // Optional: Parsed JSON for SET clause (fields to update)
        Optional<List<String>> projectionFields // Optional: List of field names for SELECT projections (e.g., ["name", "age"])
) {
    // No explicit constructors here. The canonical constructor is automatically generated by the record declaration.

    // --- Static Factory Methods for Query Construction (Vishwas Karode's preferred method) ---

    /**
     * Creates a query for operations like CREATE_COLLECTION or DELETE_COLLECTION.
     * @param type The type of the query (must be CREATE_COLLECTION or DELETE_COLLECTION).
     * @param collectionName The name of the collection.
     * @return A new Query instance.
     * @throws IllegalArgumentException If an invalid QueryType is provided.
     */
    public static Query createCollectionQuery(QueryType type, String collectionName) {
        if (type != QueryType.CREATE_COLLECTION && type != QueryType.DELETE_COLLECTION) {
            throw new IllegalArgumentException("Invalid QueryType for collection operation: " + type + ". Expected CREATE_COLLECTION or DELETE_COLLECTION.");
        }
        return new Query(type, collectionName, Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Creates a query for INSERT_DOCUMENT operations.
     * @param collectionName The name of the collection to insert into.
     * @param documentJsonString The raw JSON string of the document to insert.
     * @return A new Query instance.
     */
    public static Query createInsertQuery(String collectionName, String documentJsonString) {
        return new Query(QueryType.INSERT_DOCUMENT, collectionName, Optional.of(documentJsonString), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Creates a query for SELECT_ALL or SELECT_FILTERED operations, with optional projection.
     * @param collectionName The name of the collection to select from.
     * @param filter Optional JsonNode for WHERE clause conditions.
     * @param projectionFields Optional list of field names for projection.
     * @return A new Query instance.
     */
    public static Query createSelectQuery(String collectionName, Optional<JsonNode> filter, Optional<List<String>> projectionFields) {
        QueryType type = filter.isPresent() ? QueryType.SELECT_FILTERED : QueryType.SELECT_ALL;
        return new Query(type, collectionName, Optional.empty(), filter, Optional.empty(), projectionFields);
    }

    /**
     * Creates a query for UPDATE_DOCUMENT operations.
     * @param collectionName The name of the collection to update.
     * @param filter JsonNode for WHERE clause conditions to identify documents to update.
     * @param updateData JsonNode containing the fields and values to set.
     * @return A new Query instance.
     */
    public static Query createUpdateQuery(String collectionName, JsonNode filter, JsonNode updateData) {
        return new Query(QueryType.UPDATE_DOCUMENT, collectionName, Optional.empty(), Optional.of(filter), Optional.of(updateData), Optional.empty());
    }

    /**
     * Creates a query for DELETE_DOCUMENT operations.
     * @param collectionName The name of the collection to delete from.
     * @param filter JsonNode for WHERE clause conditions to identify documents to delete.
     * @return A new Query instance.
     */
    public static Query createDeleteDocumentQuery(String collectionName, JsonNode filter) {
        return new Query(QueryType.DELETE_DOCUMENT, collectionName, Optional.empty(), Optional.of(filter), Optional.empty(), Optional.empty());
    }
}